"use client";
import "./globals.css";
import { Poppins } from "next/font/google";
import NavBar from "../components/UI/NavBar";
import Footer from "../components/UI/Footer";
import { usePathname } from "next/navigation";

const poppins = Poppins({
  subsets: ["devanagari"],
  weight: ["300", "400", "500", "600", "700"],
});

// export const metadata = {
//   title: "Libot - Easy Online Hotel Bookings",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  let bgColor = "";
  let navBarClasses = "text-black";
  if (pathname === "/") {
    bgColor = "bg-libot-yellow";
  } else if (pathname === "/pricing") {
    bgColor = "bg-libot-green";
    navBarClasses = "text-white";
  } else if (pathname === "/about") {
    bgColor = "bg-libot-blue";
    navBarClasses = "text-white";
  } else if (pathname === "/features") {
    bgColor = "bg-libot-yellow";
  }
  return (
    <html lang="en">
      <body className={`${poppins.className} transiton-all`}>
        <div className={bgColor}>
          <NavBar navBarClasses={navBarClasses} />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
